---
name: Test cases
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade-pip
          pip install -r requirements.txt
      - name: Test code
        run: pytest tests/test.py
